"""set short_url to null

Revision ID: b67f3440b4b5
Revises: 8304558aeb0f
Create Date: 2025-10-18 17:29:05.774980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67f3440b4b5'
down_revision: Union[str, Sequence[str], None] = '8304558aeb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_url',
               existing_type=sa.VARCHAR(length=265),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'short_url',
               existing_type=sa.VARCHAR(length=265),
               nullable=False)
    # ### end Alembic commands ###
